name: Package exe with PyInstaller - Windows

on:
  push:
    branches: [ release ]

jobs:
  build-linux:
    runs-on: ubuntu-latest 

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: install pyinstaller 
      run: pip install pyinstaller 

    - name: run pyinstaller 
      run: cd PyGame && 
        pyinstaller --windowed --onefile orso_ai.py --add-data "bear_v2.policy:." --add-data "sounds/*:sounds/" --add-data "images/*:images/" --add-data "fonts/*:fonts/" --icon="images/little-bear.ico"

    - uses: actions/upload-artifact@v2
      with:
        name: orso_ai.elf
        path: PyGame/dist